#!/usr/bin/env python3
"""
makecheck.py - Parse a GNU Makefile (hand-written, or generated by
autoconf/automake after running ./configure) to find what it actually
links against, what programs it invokes, and what pkg-config modules it
queries - then map each to a Debian package and check install status.

Part of deb-buildcheck-suite. Shares its package/program/library
resolution with configcheck.py (must be in the same directory).

Usage: ./makecheck.py /path/to/Makefile [--json] [-o FILE]
"""

import argparse
import contextlib
import json
import os
import re
import shutil
import sys

try:
    from configcheck import (
        Column, render_table, get_term_width,
        resolve_program, resolve_library, resolve_package, HAVE_APTFILE,
        Check, VersionReq, MODVER_TOKEN_RE, have_cell, describe_contents_files,
    )
except ModuleNotFoundError:
    print("error: configcheck.py not found - makecheck.py shares its package/program/library",
          file=sys.stderr)
    print("resolution logic with it, so both files need to be in the same directory.",
          file=sys.stderr)
    sys.exit(1)

# ---------------------------------------------------------------------------
# Stage 1: read the file, join backslash line-continuations, strip comments,
# and split into "variable assignment" lines vs "recipe" lines (indented
# with a real TAB - that's significant in Make, not just style) vs
# everything else (target lines, directives, blank lines - ignored).
# ---------------------------------------------------------------------------
ASSIGN_RE = re.compile(r'^([A-Za-z0-9_.]+)\s*(::=|:=|\+=|\?=|=)\s*(.*)$')


def _strip_comment(line: str) -> str:
    # a bare # starts a comment; \# is a literal hash. Good enough for real
    # Makefiles without going down the path of a full shell-quote parser.
    out = []
    escaped = False
    for ch in line:
        if escaped:
            out.append(ch)
            escaped = False
            continue
        if ch == "\\":
            escaped = True
            out.append(ch)
            continue
        if ch == "#":
            break
        out.append(ch)
    return "".join(out)


def _join_continuations(text: str) -> list[str]:
    raw_lines = text.split("\n")
    joined = []
    buf = ""
    for line in raw_lines:
        if buf:
            line = buf + " " + line.lstrip()
            buf = ""
        if line.endswith("\\"):
            buf = line[:-1]
            continue
        joined.append(line)
    if buf:
        joined.append(buf)
    return joined


def parse_makefile(text: str) -> tuple[dict[str, list[str]], list[str]]:
    """Returns (variables, recipe_lines). `variables` maps name -> list of
    raw (unexpanded) value fragments in assignment order (later '='
    reassigns/overrides; '+=' appends; first '?=' wins if not already set -
    handled properly during expansion, not here)."""
    variables: dict[str, list[tuple[str, str]]] = {}
    recipes: list[str] = []

    lines = _join_continuations(text)
    for raw_line in lines:
        if raw_line.startswith("\t"):
            recipes.append(_strip_comment(raw_line[1:]))
            continue

        line = _strip_comment(raw_line).rstrip()
        if not line.strip():
            continue

        m = ASSIGN_RE.match(line)
        if m:
            name, op, value = m.groups()
            variables.setdefault(name, []).append((op, value.strip()))

    return variables, recipes


# ---------------------------------------------------------------------------
# Stage 2: collapse each variable's assignment history into one resolved
# value ('=' overrides, '+=' appends, '?=' only applies if nothing set it
# yet), then recursively expand $(VAR)/${VAR} references. $(shell ...) and
# other Make functions are left as opaque text - we can't safely execute
# them, but pkg-config extraction (below) still scans inside them as text.
# ---------------------------------------------------------------------------
VAR_REF_RE = re.compile(r'\$[({]([A-Za-z0-9_.]+)[)}]')


def build_variable_values(variables: dict[str, list[tuple[str, str]]]) -> dict[str, str]:
    resolved: dict[str, str] = {}
    for name, assignments in variables.items():
        value, have_value = "", False
        for op, val in assignments:
            if op == "?=":
                if not have_value:
                    value, have_value = val, True
            elif op == "+=":
                value, have_value = ((value + " " + val) if have_value else val), True
            else:  # '=', ':=', '::='
                value, have_value = val, True
        resolved[name] = value
    return resolved


def expand(text: str, values: dict[str, str], _stack: frozenset = frozenset(), _depth: int = 0) -> str:
    if _depth > 20 or not text:
        return text

    def repl(m: re.Match) -> str:
        name = m.group(1)
        if name in _stack:
            return ""  # self-referential variable - break the cycle
        if name not in values:
            # a variable never assigned anywhere in this file - almost
            # always one GNU Make itself supplies at runtime (MAKE,
            # MAKEFLAGS, MAKELEVEL, CURDIR, SHELL...) or one meant to come
            # from the environment. Silently treating it as empty would
            # shift every token after it in the recipe - e.g.
            # "$(MAKE) $(AM_MAKEFLAGS) all-recursive" collapsing to just
            # "all-recursive" and getting misread as the invoked program.
            # Leaving the reference literal keeps the real first token out
            # of view, and the '$' it still contains makes the existing
            # "unresolved expansion" guards downstream skip the line
            # instead of guessing.
            return m.group(0)
        return expand(values.get(name, ""), values, _stack | {name}, _depth + 1)

    return VAR_REF_RE.sub(repl, text)


# ---------------------------------------------------------------------------
# Stage 3: pull real signal out of the fully-expanded text - variable
# values AND recipe lines together, since a flag might live in either
# (some Makefiles hardcode flags directly in a recipe rather than a
# variable).
# ---------------------------------------------------------------------------
LIB_FLAG_RE = re.compile(r'(?<![A-Za-z0-9_-])-l([A-Za-z0-9_+]+)')
# a bare regex can't tell "-lfoo" (link against libfoo) apart from find(1)'s
# "-links N" / "-lname PATTERN" predicates by shape alone - both are
# literally "-l" + letters. These two are common enough in Makefile
# `find` invocations (e.g. a `find ... -links 1 ...` permissions fixup)
# to be worth a denylist rather than false-flagging a library that isn't
# one; a real "-links"/"-lname" library is not known to exist. Also
# covers the ordinary English words "-linux" and "-link" showing up in
# unrelated text (a comment, an echo, a platform-conditional check) -
# the same false positive found and fixed in configcheck.py's identical
# regex.
FIND_FLAG_FALSE_POSITIVES = {"inks", "name", "inux", "ink"}
INCLUDE_FLAG_RE = re.compile(r'-I\s*(\S+)')
PKGCONFIG_CALL_RE = re.compile(r'\bpkg-config\b([^`)\n]*)')
# a captured call's text can run on past pkg-config's own arguments into
# a chained shell command - e.g. "pkg-config --exists 'foo' && echo yes
# || echo no" - without truncating there, "echo"/"yes"/"no" get picked
# up as if they were bare module names
CALL_CHAIN_SPLIT_RE = re.compile(r'&&|\|\||;|\|')
PKGCONFIG_ARG_RE = re.compile(r'(?<!\S)([A-Za-z][A-Za-z0-9+._-]*(?:>=?[0-9.]+)?)')
# --atleast-version=1.2.3 foo (also --exact-version=/--max-version=) - the
# version and the module name appear as two separate CLI args rather than
# one "mod op ver" token the way an inline spec does
VERSIONFLAG_RE = re.compile(
    r'--(atleast-version|exact-version|max-version)=?\s*([0-9][0-9A-Za-z_.+-]*)'
)
VERSIONFLAG_OP = {"atleast-version": ">=", "exact-version": "=", "max-version": "<="}

# Make has no pkg-config-style version-comparison syntax at all, so a
# Makefile that wants to gate the build on a tool's version has to
# hand-roll it - overwhelmingly often as: probe the tool's version into
# one variable ("GCC_VER := $(shell gcc -dumpversion)"), state the
# minimum in a second, separately-named variable ("REQ_GCC_VER := 10.0"),
# then compare the two via $(sort ...)/$(firstword ...)/ifneq, or an
# equivalent shell/awk one-liner. There's no single call-site to match
# the way there is for pkg-config; what IS reliably there is the probe
# assignment and the requirement assignment, correlated by sharing the
# same "stem" in their variable names (GCC_VER / REQ_GCC_VER). This is a
# heuristic, same spirit as configcheck's AX_COMPARE_VERSION handling -
# it misses a comparison whose requirement variable doesn't share a
# recognizable name, but the probed program is still reported with
# whatever HAVE version can be resolved either way.
SHELL_VERSION_PROBE_RE = re.compile(
    r'([A-Za-z_][A-Za-z0-9_]*)\s*(?::=|::=|\?=|\+=|=)\s*'
    r'\$\(shell\s+([A-Za-z0-9_./+-]+)\s+(?:-dumpversion|--version|-version)\b[^)]*\)'
)
LITERAL_VERSION_ASSIGN_RE = re.compile(
    r'^[ \t]*([A-Za-z_][A-Za-z0-9_]*)\s*(?::=|::=|\?=|\+=|=)\s*([0-9]+(?:\.[0-9]+){0,3})\s*(?:#.*)?$',
    re.MULTILINE,
)
REQUIREMENT_NAME_TAGS = ("REQ", "MIN", "NEED")


def extract_makefile_version_reqs(text: str) -> "dict[str, VersionReq]":
    """Program name -> VersionReq, for the hand-rolled probe-vs-requirement
    idiom described above. Only a minimum-version check (>=) is inferred,
    since that's what every real-world instance of this idiom checks for -
    a hand-rolled MAX or exact-version gate would need its own comparison
    shape entirely and isn't covered here."""
    literal_vars = dict(LITERAL_VERSION_ASSIGN_RE.findall(text))
    results: "dict[str, VersionReq]" = {}
    for m in SHELL_VERSION_PROBE_RE.finditer(text):
        varname, prog = m.groups()
        stem = re.sub(r'_(VER|VERSION)$', '', varname, flags=re.IGNORECASE).upper()
        req_var = next(
            (name for name in literal_vars
             if stem in name.upper() and any(tag in name.upper() for tag in REQUIREMENT_NAME_TAGS)),
            None,
        )
        if req_var:
            prog_name = os.path.basename(prog)
            results[prog_name] = VersionReq(op=">=", version=literal_vars[req_var],
                                             source=f"Makefile var {req_var}")
    return results

# shell builtins/keywords that legitimately appear as the first word of a
# recipe line but aren't separately-installed programs - resolving these
# would either crash on a non-existent "package" or produce noise
SHELL_BUILTINS = {
    "cd", "test", "if", "then", "else", "fi", "for", "do", "done", "echo",
    "true", "false", ":", "exit", "set", "export", "unset", "eval", "case",
    "esac", "while", "until", "in", "return", "shift", "read", "exec",
}

# common Make tool variables worth checking even if they never happen to
# be the literal first word of a captured recipe (e.g. used mid-recipe,
# or only in a target that wasn't reached by this simple line scan)
TOOL_VARS = ["CC", "CXX", "AR", "RANLIB", "STRIP", "LD", "AS", "NM",
             "OBJCOPY", "OBJDUMP", "YACC", "LEX", "PKG_CONFIG"]


def extract_libraries(blob: str) -> list[str]:
    return sorted(set(LIB_FLAG_RE.findall(blob)) - FIND_FLAG_FALSE_POSITIVES)


def extract_include_paths(blob: str) -> list[str]:
    return sorted(set(INCLUDE_FLAG_RE.findall(blob)))


def extract_pkgconfig_modules(blob: str) -> "dict[str, VersionReq | None]":
    """Module name -> version requirement (or None if the call names the
    module with no version constraint)."""
    modules: "dict[str, VersionReq | None]" = {}

    for raw_call in PKGCONFIG_CALL_RE.findall(blob):
        call = CALL_CHAIN_SPLIT_RE.split(raw_call, maxsplit=1)[0]

        # inline "mod >= 1.2.3" specs, e.g. pkg-config --exists 'foo >= 1.2'
        for m in MODVER_TOKEN_RE.finditer(call):
            mod, op, ver = m.groups()
            modules[mod] = VersionReq(op=op, version=ver, source="pkg-config")

        # --atleast-version=1.2.3 style flag, applying to the first plain
        # module-name token elsewhere in the same call
        fm = VERSIONFLAG_RE.search(call)
        if fm:
            op = VERSIONFLAG_OP[fm.group(1)]
            ver = fm.group(2)
            for tok in call.split():
                tok = tok.strip("()}{'\"")
                if not tok or tok.startswith("-") or "=" in tok or tok == "pkg-config":
                    continue
                if PKGCONFIG_ARG_RE.fullmatch(tok) and tok not in modules:
                    modules[tok] = VersionReq(op=op, version=ver, source="pkg-config")
                    break

        # bare module names with no version constraint at all - excludes
        # the literal word "pkg-config" itself, which shows up as an
        # ordinary token when a line invokes it more than once (e.g.
        # "pkg-config --exists foo && pkg-config --cflags foo")
        for tok in call.split():
            tok = tok.strip("()}{'\"")
            if not tok or tok.startswith("-") or tok == "pkg-config":
                continue
            if PKGCONFIG_ARG_RE.fullmatch(tok) and tok not in modules:
                modules[tok] = None

    return dict(sorted(modules.items()))


def extract_programs(recipes: list[str], values: dict[str, str]) -> list[str]:
    programs: set[str] = set()

    for var in TOOL_VARS:
        val = expand(values.get(var, ""), values).strip()
        # a tool var can hold "name arg1 arg2" (e.g. "gcc -m32") - only the
        # first token is the actual program
        first = val.split()[0] if val.split() else ""
        if first and "$" not in first:
            programs.add(first)

    REDIRECT_TOKEN_RE = re.compile(r'^[0-9]*(>>?|<)&?[0-9]*\S*$')

    for recipe in recipes:
        line = expand(recipe, values).strip()
        line = line.lstrip("@-+({").strip()  # Make's per-recipe echo/error/job-server prefixes,
                                              # plus a leading subshell-opening '(' or a POSIX
                                              # shell brace-group opener '{' - neither is ever
                                              # itself the command being run
        if not line:
            continue
        tokens = line.split()
        # a redirection can legally appear as a prefix before the actual
        # command word in POSIX shell (e.g. "{ >&2 echo ...; }") - skip
        # past any leading redirection-shaped tokens to find the real one
        tokens = [t for t in tokens if not REDIRECT_TOKEN_RE.match(t)]
        if not tokens:
            continue
        first = tokens[0]
        # a relative path (contains '/' but isn't rooted at '/') almost
        # always points at something the project just built or a script
        # living in its own tree (e.g. "frontend/mp3x$(EXEEXT)") - not a
        # system dependency apt could ever resolve, so basename-matching
        # it against dpkg would only produce noise or a false match on an
        # unrelated system binary with the same name. An absolute path
        # like "/usr/bin/ld" is kept - that one's a real system lookup.
        if not first or "$" in first or ("/" in first and not first.startswith("/")):
            continue
        # a bare assignment inside a recipe (VAR=value cmd) isn't a program
        if "=" in first:
            continue
        name = first.rsplit("/", 1)[-1]  # invoked via a path - check the basename
        if name and name not in SHELL_BUILTINS:
            programs.add(name)

    return sorted(programs)

# ---------------------------------------------------------------------------
# Stage 4: put it all together and resolve each item to a Debian package,
# reusing configcheck's resolvers exactly - a Makefile's -lfoo means the
# same thing a configure script's "in -lfoo" check does.
# ---------------------------------------------------------------------------
def summarize_reports(reports: list[dict]) -> dict:
    """Merge per-Makefile reports from a tree walk into one deduplicated
    list per category. The same toolchain program, system library, or
    pkg-config module shows up in nearly every subdirectory's Makefile in
    a typical autotools tree - gcc, ar, ranlib, rm... - so after the first
    occurrence, repeating it N more times adds nothing."""
    def dedupe(rows: list[dict], key: str = "name") -> list[dict]:
        seen: dict = {}
        for row in rows:
            seen.setdefault(row[key], row)
        return [seen[k] for k in sorted(seen)]

    libraries: list[dict] = []
    programs: list[dict] = []
    pkgconfig: list[dict] = []
    includes: list[dict] = []
    for r in reports:
        libraries.extend(r["libraries"])
        programs.extend(r["programs"])
        pkgconfig.extend(r["pkgconfig"])
        includes.extend(r["includes"])

    return {
        "libraries": dedupe(libraries),
        "programs": dedupe(programs),
        "pkgconfig": dedupe(pkgconfig),
        "includes": dedupe(includes, key="path"),
    }


def build_report(makefile_path: str) -> dict:
    text = open(makefile_path, "r", errors="replace").read()
    variables, recipes = parse_makefile(text)
    values = build_variable_values(variables)

    expanded_values = [expand(v, values) for v in values.values()]
    expanded_recipes = [expand(r, values) for r in recipes]
    blob = "\n".join(expanded_values + expanded_recipes)

    libs = extract_libraries(blob)
    includes = extract_include_paths(blob)
    modules = extract_pkgconfig_modules(blob)
    programs = set(extract_programs(recipes, values))

    version_reqs = extract_makefile_version_reqs(text)
    # a version-gated tool (e.g. "GCC_VER := $(shell gcc -dumpversion)")
    # might never appear as a recipe's first word or a TOOL_VARS entry at
    # all - the Makefile only invokes it inside $(shell ...) to read its
    # version - so it needs adding here or it wouldn't be reported as a
    # dependency at all, requirement or not
    programs |= version_reqs.keys()

    library_rows = []
    for lib in libs:
        pkg, installed, note = resolve_library(lib)
        check = Check(name=lib, type="library", guard="UNCONDITIONAL")
        # a bare "-lfoo" carries no version syntax at all - unlike autoconf's
        # "checking for X >= 1.2.3" messages, Makefiles have no way to state
        # a requirement here, so WANT is always "-"; HAVE (what's actually
        # on the machine) is still worth showing regardless
        library_rows.append(dict(name=lib, package=pkg, installed=installed, note=note,
                                  want="-", have=have_cell(check, pkg)))

    program_rows = []
    for prog in sorted(programs):
        pkg, installed, note = resolve_program(prog)
        req = version_reqs.get(prog)
        check = Check(name=prog, type="generic", guard="UNCONDITIONAL", version_req=req)
        prog_path = shutil.which(prog)
        program_rows.append(dict(name=prog, package=pkg, installed=installed, note=note,
                                  want=f"{req.op}{req.version}" if req else "-",
                                  have=have_cell(check, pkg, resolved_prog_path=prog_path)))

    pkgconfig_rows = []
    for mod, req in modules.items():
        pkg, installed, note = resolve_package(f"{mod}.pc")
        check = Check(name=mod, type="pkgconfig", guard="UNCONDITIONAL", version_req=req)
        row = dict(name=mod, package=pkg, installed=installed, note=note,
                   want=f"{req.op}{req.version}" if req else "-",
                   have=have_cell(check, pkg))
        pkgconfig_rows.append(row)

    return {
        "libraries": library_rows,
        "programs": program_rows,
        "pkgconfig": pkgconfig_rows,
        "includes": [{"path": inc, "exists": os.path.isdir(inc) or os.path.isfile(inc)} for inc in includes],
    }


def print_report(report: dict, makefile_path: str, width: int | None = None) -> None:
    term_width = width if width is not None else get_term_width()
    cols = [
        Column("CHECKS FOR", "name", min_width=12, flexible=True, shrink_priority=1),
        Column("PACKAGE", "package", min_width=14, flexible=True, shrink_priority=2),
        Column("INST?", "installed", min_width=5),
        Column("WANT", "want", min_width=6, flexible=True, shrink_priority=4),
        Column("HAVE", "have", min_width=10, flexible=True, shrink_priority=3),
        Column("NOTE", "note", min_width=0, flexible=True, shrink_priority=0),
    ]
    pkgconfig_cols = [
        Column("MODULE", "name", min_width=12, flexible=True, shrink_priority=1),
        Column("PACKAGE", "package", min_width=14, flexible=True, shrink_priority=2),
        Column("INST?", "installed", min_width=5),
        Column("WANT", "want", min_width=6, flexible=True, shrink_priority=4),
        Column("HAVE", "have", min_width=10, flexible=True, shrink_priority=3),
        Column("NOTE", "note", min_width=0, flexible=True, shrink_priority=0),
    ]

    def section(title: str, rows: list[dict], columns: list = cols) -> None:
        print("=" * min(78, term_width))
        print(f" {title}")
        print("=" * min(78, term_width))
        if not rows:
            print(render_table(columns, [], width=term_width))
            print("  (none found)")
        else:
            print(render_table(columns, rows, width=term_width))
        print()

    print(f"Parsed: {makefile_path}")
    print()
    section("Libraries linked (-l flags)", report["libraries"])
    section("Programs invoked", report["programs"])
    section("pkg-config modules queried", report["pkgconfig"], columns=pkgconfig_cols)

    print("=" * min(78, term_width))
    print(" -I include paths referenced (informational - not package-resolved)")
    print("=" * min(78, term_width))
    inc_cols = [
        Column("PATH", "path", min_width=12, flexible=True, shrink_priority=0),
        Column("EXISTS HERE?", "exists_str", min_width=12),
    ]
    inc_rows = [{"path": i["path"], "exists_str": "yes" if i["exists"] else "no"} for i in report["includes"]]
    if not inc_rows:
        print(render_table(inc_cols, [], width=term_width))
        print("  (none found)")
    else:
        print(render_table(inc_cols, inc_rows, width=term_width))

    if not HAVE_APTFILE:
        print()
        print("Note: apt-file not found - package discovery for anything not already")
        print("installed will show '?'. Install with: sudo apt install apt-file && sudo apt-file update")


MAKEFILE_NAMES = {"Makefile", "makefile", "GNUmakefile"}


def find_makefiles(root: str) -> list[str]:
    found = []
    for dirpath, dirnames, filenames in os.walk(root):
        # skip VCS/hidden dirs - never meaningful build locations, just noise
        dirnames[:] = [d for d in dirnames if not d.startswith(".")]
        for name in filenames:
            if name in MAKEFILE_NAMES:
                found.append(os.path.join(dirpath, name))
    return sorted(found)


def main() -> int:
    ap = argparse.ArgumentParser(description="Parse a Makefile and map what it actually links/invokes to Debian packages.")
    ap.add_argument("makefile", help="path to a Makefile, or a directory to search recursively for all Makefiles")
    ap.add_argument("--json", action="store_true", help="emit JSON instead of the text report")
    ap.add_argument("-o", "--output", metavar="FILE",
                     help="write the report to FILE instead of the terminal - columns are never "
                          "truncated when writing to a file")
    args = ap.parse_args()

    if os.path.isdir(args.makefile):
        paths = find_makefiles(args.makefile)
        if not paths:
            print(f"error: no Makefile found under {args.makefile}", file=sys.stderr)
            return 1
    elif os.path.isfile(args.makefile):
        paths = [args.makefile]
        basename = os.path.basename(args.makefile)
        if basename not in MAKEFILE_NAMES:
            print(f"warning: '{basename}' doesn't look like a Makefile name "
                  f"(expected one of: {', '.join(sorted(MAKEFILE_NAMES))})", file=sys.stderr)
            print("makecheck.py parses Makefile syntax specifically - a configure script or "
                  "other file will just produce noise. Use configcheck.py for configure scripts.",
                  file=sys.stderr)
            if sys.stdin.isatty():
                answer = input("Continue anyway? [y/N] ").strip().lower()
                if answer not in ("y", "yes"):
                    print("aborted.", file=sys.stderr)
                    return 1
            else:
                print("(non-interactive input - proceeding anyway; pass a real Makefile to skip this warning)",
                      file=sys.stderr)
    else:
        print(f"error: no such file or directory: {args.makefile}", file=sys.stderr)
        return 1

    print(describe_contents_files(), file=sys.stderr)

    def emit_text(width: int | None = None) -> None:
        reports = []
        for i, path in enumerate(paths):
            if len(paths) > 1:
                directory = os.path.dirname(path) or "."
                bar = "#" * min(78, width if width is not None else get_term_width())
                print(bar)
                print(f"# Directory: {directory}")
                print(bar)
                print()
                sys.stdout.flush()  # show the announcement before the (possibly slow) parse runs
            report = build_report(path)
            reports.append(report)
            print_report(report, path, width=width)
            sys.stdout.flush()
            if i < len(paths) - 1:
                print()

        if len(paths) > 1:
            term_width = width if width is not None else get_term_width()
            bar = "#" * min(78, term_width)
            print()
            print(bar)
            print(f"# Summary - deduplicated across all {len(paths)} Makefiles")
            print(bar)
            print()
            print_report(summarize_reports(reports), f"{len(paths)} Makefiles (deduplicated)", width=width)

    def emit_json() -> str:
        reports = [(p, build_report(p)) for p in paths]  # JSON needs a complete document either way
        if len(reports) == 1:
            return json.dumps(reports[0][1], indent=2)
        return json.dumps(
            {
                "directories": [{"directory": os.path.dirname(p) or ".", "makefile": p, **r} for p, r in reports],
                "summary": summarize_reports([r for _, r in reports]),
            },
            indent=2,
        )

    if args.output:
        with open(args.output, "w") as f:
            with contextlib.redirect_stdout(f):
                if args.json:
                    print(emit_json())
                else:
                    emit_text(width=1000)
        print(f"Report written to {args.output}")
    elif args.json:
        print(emit_json())
    else:
        emit_text()
    return 0


if __name__ == "__main__":
    sys.exit(main())
